# Generated by Django 4.1.1 on 2022-09-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0002_passage_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="passage_id",
            new_name="passage",
        ),
    ]
