# Generated by Django 4.1.1 on 2022-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writing",
            name="content",
            field=models.CharField(max_length=500, verbose_name="tast description"),
        ),
    ]
