# Generated by Django 4.1.1 on 2022-09-09 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("E", "Easy"), ("M", "Medium"), ("H", "Hard")],
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="untitled", max_length=50, verbose_name="passage title"
                    ),
                ),
                (
                    "audio_src",
                    models.FileField(
                        upload_to="audios",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[".mp3", ".wav", ".aac", "ogg"]
                            )
                        ],
                        verbose_name="audio file",
                    ),
                ),
            ],
        ),
    ]
